#!/usr/bin/env bash
#Install nginx
#Nginx should be listening on port 80

#Update the package list
sudo apt-get update

#Install Nginx
sudo apt-get -y install nginx

#Start Nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html
