#!/usr/bin/env bash
# Automating the nginx configuration
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By 161688-web-01;" //etc/nginx.conf
sudo service nginx restart
