#!/usr/bin/env bash
#install and configure HAproxy on server

apt-get update

add-apt-repository ppa:vbernat/haproxy-2.6 -y

apt-get update
apt-get install haproxy=2.6.\* -y

systemctl enable haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 161688-web-01 54.152.57.180:80 check
    server 161688-web-02 3.84.239.204:80 check
" >> /etc/haproxy/haproxy.cfg

systemctl restart haproxy
