#!/usr/bin/env bash
#install and configure HAproxy on server

sudo apt-get -y install software-properties-common

sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y

sudo apt-get update

sudo apt-get install haproxy=2.6.\* -y

echo "
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 161688-web-01 18.207.1.109:80 check
    server 161688-web-02 100.25.148.35:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
