#!/usr/bin/env bash
# A bash script

function create_file()
{
	sudo touch /var/run/myscript.pid
	sudo chown "$USER":"$USER" /var/run/myscript.pid
	echo $$ > /var/run/myscript.pid
}

function delete_file()
{
	sudo rm /var/run/myscript.pid
	exit
}

create_file

trap 'echo "I hate the kill command"; delete_file' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap delete_file SIGQUIT

while true
do
	echo "To infinity and beyond"
done
