#!/usr/bin/env bash
# Displays numbers from 1 to 100
x=1
a=0
while [ $x -le 100 ]
do
	if [ "$((x % 3))" -eq $a ] && [ "$((x % 5))" -eq $a ]
	then
		echo "FizzBuzz"
	elif [ "$((x % 3))" -eq $a ]
	then
		echo "Fizz"
	elif [ "$((x % 5))" -eq $a ]
	then
		echo "Buzz"
	else
		echo "$x"
	fi
	x=$((x + 1))
done
