#!/usr/bin/env bash
# Configures an Ubuntu server with the below requirements
cp /etc/hosts /etc/hosts.new
sed -i 's/^127.*$/127.0.0.2	localhost/' /etc/hosts.new
sed -i -e '$a8.8.8.8	facebook.com' /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
