#!/usr/bin/env bash
# Run Nginx as nginx user
chown nginx /etx/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
